name: CI

on:
  push:
    branches: [main]
    paths:
      - '.github/**'
      - '.pre-commit-config.yaml'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'app/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/**'
      - '.pre-commit-config.yaml'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'app/**'
  workflow_dispatch:

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install Python dependencies
        run: |
          pip install -r requirements.dev.txt

      - name: Run pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit run --all-files --verbose

  test:
    needs: precommit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install Python dependencies
        run: |
          pip install -r requirements.dev.txt

      - name: Run tests
        run: ./scripts/test.sh
        timeout-minutes: 3
